### PR TITLE
Update closure to latest version: 20180101

### PR DESCRIPTION
**Pull request by bacher09**
I updated closure compiler to latest version. Also, seems `package-lock.json` should be updated. It still have old version: `2.1.4`.

### CODE REVIEW

**Comment by bacher09** [comment]
I rolled back change for `google-closure-compiler-js` since it crashed tests on travis.

**Comment by roman01la** [comment]
Thanks. Both js and jvm compiler should be of the same version. Need to investigate why js tests are broken.

**Comment by bacher09** [comment]
I have found what caused this issue. Seems js version of closure-compiler have changed input format for `externs` option. Tomorrow I will update this PR with fix that will be backward compatible.

**Comment by roman01la** [comment]
@bacher09 Is it ready to merge?

**Comment by bacher09** [comment]
Yes, I updated PR.

**Comment by roman01la** [comment]
Great, thanks!

**Pull request merged**
